'use strict';
const APP_CACHE='jcf-offline-v3';
const STORAGE_KEY='jcf_registros_v3';
const OCR={script:'https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/tesseract.min.js',worker:'https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/worker.min.js',coreDir:'https://cdn.jsdelivr.net/npm/tesseract.js-core@6.1.2',langDir:'https://tessdata.projectnaptha.com/4.0.0_best',langFile:'https://tessdata.projectnaptha.com/4.0.0_best/spa.traineddata.gz',assets:['https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/tesseract.min.js','https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/worker.min.js','https://cdn.jsdelivr.net/npm/tesseract.js-core@6.1.2/tesseract-core.wasm.js','https://cdn.jsdelivr.net/npm/tesseract.js-core@6.1.2/tesseract-core-lstm.wasm.js','https://cdn.jsdelivr.net/npm/tesseract.js-core@6.1.2/tesseract-core-simd.wasm.js','https://cdn.jsdelivr.net/npm/tesseract.js-core@6.1.2/tesseract-core-simd-lstm.wasm.js','https://tessdata.projectnaptha.com/4.0.0_best/spa.traineddata.gz']};
let sourceImage=null,imageObjectUrl=null,worker=null,crop={x:0,y:0,w:0,h:0},display={scale:1,w:0,h:0},drag=null,rotation=0;
const cropCanvas=document.getElementById('cropCanvas'),cropCtx=cropCanvas.getContext('2d',{willReadFrequently:true});
function setStatus(id,text,kind='ok'){const el=document.getElementById(id);el.textContent=text;el.style.display='block';el.className='status'+(kind==='error'?' error':kind==='warn'?' warn':'')}
function hideStatus(id){document.getElementById(id).style.display='none'}
function setProgress(wrapperId,barId,value){const wrap=document.getElementById(wrapperId),bar=document.getElementById(barId);wrap.style.display=value===null?'none':'block';if(value!==null)bar.style.width=Math.max(0,Math.min(100,value))+'%'}
function updateConnection(){const el=document.getElementById('connection'),online=navigator.onLine;el.textContent=online?'En línea':'Sin internet';el.classList.toggle('offline',!online)}
window.addEventListener('online',updateConnection);window.addEventListener('offline',updateConnection);updateConnection();
async function registerServiceWorker(){if(!('serviceWorker'in navigator))return null;try{return await navigator.serviceWorker.register('./sw.js',{scope:'./'})}catch(err){console.warn('No se pudo registrar el modo offline',err);return null}}
registerServiceWorker();
async function isOfflineReady(){if(!('caches'in window))return false;const cache=await caches.open(APP_CACHE),checks=await Promise.all(OCR.assets.map(url=>cache.match(url)));return checks.every(Boolean)}
async function refreshOfflineState(){if(await isOfflineReady()){setStatus('offlineStatus','Lector offline preparado. Ya puedes usarlo sin señal.');document.getElementById('offlineBtn').textContent='Lector offline listo'}}
refreshOfflineState();
document.getElementById('offlineBtn').addEventListener('click',prepareOffline);
async function prepareOffline(){if(!navigator.onLine){setStatus('offlineStatus','Conéctate una sola vez para descargar el lector.','warn');return}const btn=document.getElementById('offlineBtn');btn.disabled=true;hideStatus('offlineStatus');setProgress('offlineProgress','offlineBar',1);try{await registerServiceWorker();if('serviceWorker'in navigator)await navigator.serviceWorker.ready;const cache=await caches.open(APP_CACHE);for(let i=0;i<OCR.assets.length;i++){const url=OCR.assets[i],cached=await cache.match(url);if(!cached){const response=await fetch(url,{mode:'cors',cache:'reload'});if(!response.ok)throw new Error('No se pudo descargar un componente');await cache.put(url,response.clone())}setProgress('offlineProgress','offlineBar',Math.round(((i+1)/OCR.assets.length)*88))}await getWorker(true);setProgress('offlineProgress','offlineBar',100);setStatus('offlineStatus','¡Listo! El lector quedó descargado para trabajar sin internet.');btn.textContent='Lector offline listo'}catch(err){console.error(err);setStatus('offlineStatus','No se completó la descarga. Revisa el internet e inténtalo otra vez.','error')}finally{btn.disabled=false;setTimeout(()=>setProgress('offlineProgress','offlineBar',null),1000)}}
async function getWorker(warmup=false){if(worker)return worker;if(typeof Tesseract==='undefined')throw new Error('El lector OCR no está disponible');worker=await Tesseract.createWorker('spa',1,{workerPath:OCR.worker,corePath:OCR.coreDir,langPath:OCR.langDir,logger:m=>{if(!warmup&&m.status==='recognizing text'){const p=15+Math.round((m.progress||0)*80);setProgress('ocrProgress','ocrBar',p);setStatus('ocrStatus','Leyendo la cédula… '+Math.round((m.progress||0)*100)+'%')}}});return worker}
