document.getElementById('cedulaFoto').addEventListener('change',async e=>{const file=e.target.files&&e.target.files[0];if(!file)return;clearImageMemory();imageObjectUrl=URL.createObjectURL(file);const img=new Image();img.onload=()=>{sourceImage=img;rotation=0;document.getElementById('editorWrap').style.display='block';resetCrop();setStatus('ocrStatus','Ajusta el recuadro azul alrededor de la cédula y pulsa “Leer cédula”.','warn')};img.onerror=()=>setStatus('ocrStatus','No pude abrir esa fotografía.','error');img.src=imageObjectUrl});
function sourceDimensions(){return rotation%180===0?{w:sourceImage.naturalWidth,h:sourceImage.naturalHeight}:{w:sourceImage.naturalHeight,h:sourceImage.naturalWidth}}
function drawRotatedImage(ctx,img,rotation,w,h){ctx.save();if(rotation===0)ctx.drawImage(img,0,0,w,h);else if(rotation===90){ctx.translate(w,0);ctx.rotate(Math.PI/2);ctx.drawImage(img,0,0,h,w)}else if(rotation===180){ctx.translate(w,h);ctx.rotate(Math.PI);ctx.drawImage(img,0,0,w,h)}else{ctx.translate(0,h);ctx.rotate(-Math.PI/2);ctx.drawImage(img,0,0,h,w)}ctx.restore()}
function resetCrop(){if(!sourceImage)return;const d=sourceDimensions(),maxDisplay=620;display.scale=Math.min(1,maxDisplay/d.w);display.w=Math.round(d.w*display.scale);display.h=Math.round(d.h*display.scale);cropCanvas.width=display.w;cropCanvas.height=display.h;const targetW=display.w*.92,targetH=Math.min(targetW/1.586,display.h*.72);crop={x:(display.w-targetW)/2,y:(display.h-targetH)/2,w:targetW,h:targetH};drawEditor()}
function drawEditor(){if(!sourceImage)return;cropCtx.clearRect(0,0,cropCanvas.width,cropCanvas.height);drawRotatedImage(cropCtx,sourceImage,rotation,display.w,display.h);cropCtx.save();cropCtx.fillStyle='rgba(0,0,0,.56)';cropCtx.beginPath();cropCtx.rect(0,0,display.w,display.h);cropCtx.rect(crop.x,crop.y,crop.w,crop.h);cropCtx.fill('evenodd');cropCtx.strokeStyle='#0AAEF3';cropCtx.lineWidth=4;cropCtx.strokeRect(crop.x,crop.y,crop.w,crop.h);const handles=[[crop.x,crop.y],[crop.x+crop.w,crop.y],[crop.x,crop.y+crop.h],[crop.x+crop.w,crop.y+crop.h]];cropCtx.fillStyle='#fff';cropCtx.strokeStyle='#0AAEF3';cropCtx.lineWidth=3;handles.forEach(([x,y])=>{cropCtx.beginPath();cropCtx.arc(x,y,9,0,Math.PI*2);cropCtx.fill();cropCtx.stroke()});cropCtx.restore()}
function pointerPos(e){const r=cropCanvas.getBoundingClientRect();return{x:(e.clientX-r.left)*(cropCanvas.width/r.width),y:(e.clientY-r.top)*(cropCanvas.height/r.height)}}
function hitHandle(p){const pts=[['tl',crop.x,crop.y],['tr',crop.x+crop.w,crop.y],['bl',crop.x,crop.y+crop.h],['br',crop.x+crop.w,crop.y+crop.h]];return pts.find(([,x,y])=>Math.hypot(p.x-x,p.y-y)<26)?.[0]||null}
cropCanvas.addEventListener('pointerdown',e=>{if(!sourceImage)return;const p=pointerPos(e),handle=hitHandle(p);if(handle)drag={type:'resize',handle,start:p,orig:{...crop}};else if(p.x>=crop.x&&p.x<=crop.x+crop.w&&p.y>=crop.y&&p.y<=crop.y+crop.h)drag={type:'move',start:p,orig:{...crop}};if(drag){cropCanvas.setPointerCapture(e.pointerId);e.preventDefault()}});
cropCanvas.addEventListener('pointermove',e=>{if(!drag)return;const p=pointerPos(e),dx=p.x-drag.start.x,dy=p.y-drag.start.y,minW=120,minH=75,o=drag.orig;if(drag.type==='move'){crop.x=Math.max(0,Math.min(display.w-o.w,o.x+dx));crop.y=Math.max(0,Math.min(display.h-o.h,o.y+dy))}else{let x1=o.x,y1=o.y,x2=o.x+o.w,y2=o.y+o.h;if(drag.handle.includes('l'))x1=Math.min(x2-minW,Math.max(0,o.x+dx));if(drag.handle.includes('r'))x2=Math.max(x1+minW,Math.min(display.w,o.x+o.w+dx));if(drag.handle.includes('t'))y1=Math.min(y2-minH,Math.max(0,o.y+dy));if(drag.handle.includes('b'))y2=Math.max(y1+minH,Math.min(display.h,o.y+o.h+dy));crop={x:x1,y:y1,w:x2-x1,h:y2-y1}}drawEditor();e.preventDefault()});
['pointerup','pointercancel'].forEach(type=>cropCanvas.addEventListener(type,()=>drag=null));document.getElementById('resetCrop').addEventListener('click',resetCrop);document.getElementById('rotateImage').addEventListener('click',()=>{if(!sourceImage)return;rotation=(rotation+90)%360;resetCrop()});
function makeCardCanvas(){const d=sourceDimensions(),full=document.createElement('canvas');full.width=d.w;full.height=d.h;const fctx=full.getContext('2d',{willReadFrequently:true});drawRotatedImage(fctx,sourceImage,rotation,d.w,d.h);const sx=crop.x/display.scale,sy=crop.y/display.scale,sw=crop.w/display.scale,sh=crop.h/display.scale,out=document.createElement('canvas');out.width=1586;out.height=1000;out.getContext('2d',{willReadFrequently:true}).drawImage(full,sx,sy,sw,sh,0,0,out.width,out.height);full.width=1;full.height=1;return out}
