import { CIVIL_STATES, LABEL_WORDS, MONTHS, displayText, fold, normalizeCedulaOCR, normalizeDate, textualQuality, validBlood, validCivil, validSex } from './validators.js';

const stripLabels = value => displayText(value).replace(/LUGAR\s+DE\s+NACIMIENTO|FECHA\s+DE\s+NACIMIENTO|NACIONALIDAD|OCUPACIÓN|OCUPACION|FECHA\s+DE\s+EXPIRACIÓN|FECHA\s+DE\s+EXPIRACION|SEXO|TIPO\s+DE\s+SANGRE|SANGRE|ESTADO\s+CIVIL/gi, ' ').replace(/\s+/g, ' ').trim();
const field = (value, status, rules = []) => ({ value, status, rules });

export function parseCedula(text) { const result = normalizeCedulaOCR(text); return field(result.value, result.valid ? 'correcto' : result.complete ? 'revisar' : 'no detectado', [...result.rules, result.complete && !result.valid ? 'Dígito verificador dominicano inválido' : null].filter(Boolean)); }
export function parseBirthDate(text) { const anchored = fold(text).match(/FECHA\s+DE\s+NACIMIENTO\s*:?\s*(.*?)(?=FECHA\s+DE\s+EXPIRACION|$)/)?.[1] || text; const result = normalizeDate(anchored); return field(result.value, result.valid ? 'correcto' : 'no detectado', result.valid ? ['Fecha existente normalizada a DD/MM/AAAA'] : ['No se encontró una fecha de nacimiento válida']); }
export function parseSex(text) { const match = fold(text).match(/(?:^|\b)SEXO\s*:?\s*([MF])\b/); const value = validSex(match?.[1]); return field(value, value ? 'correcto' : 'no detectado', ['M/F solo se acepta asociado a la etiqueta SEXO']); }
export function parseBlood(text) { const folded = fold(text), match = folded.match(/(?:TIPO\s+DE\s+)?SANGRE\s*:?\s*(AB|A|B|O|0)\s*([+\-])/); const value = validBlood(match ? match[1] + match[2] : folded); return field(value, value ? 'correcto' : 'no detectado', ['Valor validado contra tipos sanguíneos permitidos']); }
export function parseCivil(text) { const folded = fold(text), anchored = folded.match(/ESTADO\s+CIVIL\s*:?\s*(.*?)(?=OCUPACION|FECHA\s+DE\s+EXPIRACION|$)/)?.[1] || (CIVIL_STATES.includes(folded) ? folded : ''); const value = validCivil(anchored); return field(value, value ? 'correcto' : 'no detectado', [`Valores admitidos: ${CIVIL_STATES.join(', ')}`]); }
export function parseBirthPlace(text) { const raw = fold(text).match(/LUGAR\s+DE\s+NACIMIENTO\s*:?\s*(.*?)(?=FECHA\s+DE\s+NACIMIENTO|$)/)?.[1] || text; let value = stripLabels(raw).replace(/\b(?:FECHA|NACIMIENTO)\b.*$/i, '').trim(); const quality = textualQuality(value); if (/^(?:[ILJ]\s*){4,}$/i.test(value)) value = ''; return field(value, !value ? 'no detectado' : quality >= 62 ? 'correcto' : 'revisar', [`Calidad textual: ${quality}/100`, 'Se conservaron ciudad y país']); }
export function parseNationality(text) { const raw = fold(text).match(/NACIONALIDAD\s*:?\s*(.*?)(?=SEXO|SANGRE|ESTADO\s+CIVIL|$)/)?.[1] || text; const value = stripLabels(raw).replace(/\b(SEXO|SANGRE|ESTADO)\b.*$/i, '').trim(); return field(value, textualQuality(value) >= 55 ? 'correcto' : value ? 'revisar' : 'no detectado'); }
export function parseOccupation(text) { const raw = fold(text).match(/OCUPACION\s*:?\s*(.*?)(?=FECHA\s+DE\s+EXPIRACION|$)/)?.[1] || text, foldedRaw = fold(raw); let value = stripLabels(raw).replace(/FECHA.*$/i, '').trim(); const banned = /NACIONALIDAD\s+REPUBLICA\s+DOMINICANA|^REPUBLICA\s+DOMINICANA$|\b(SEXO|SANGRE|ESTADO\s+CIVIL)\b/.test(foldedRaw) || /^REPUBLICA\s+DOMINICANA$/.test(fold(value)); if (banned) value = ''; return field(value, !value ? 'no detectado' : textualQuality(value) >= 58 ? 'correcto' : 'revisar', [banned ? 'Se rechazó una etiqueta de otro campo' : 'Valor delimitado antes de FECHA DE EXPIRACIÓN']); }

export function cleanNameCandidate(value) { return displayText(value).split(' ').filter(token => token.length > 1 && !MONTHS[fold(token)] && !LABEL_WORDS.has(fold(token))).join(' '); }
